framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            # Specific cache pool for doctrine's result_cache_driver configuration
            doctrine.result_cache_pool:
                adapter: cache.app

            # Specific pool for doctrine's system_cache_pool configuration (entites metadata interpretation)
            doctrine.system_cache_pool:
                adapter: cache.system
            
            # Specific pool for usage data
            usages_cache:
                adapter: cache.app
                # No default lifetime is provided
                # The pool will be deleted by the GitHub Workflow that is in charge of updating usages
                # default_lifetime: 1296000
