doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App

    dql:
      string_functions:
        REPLACE: App\DBAL\Replace
        IFNULL: App\DBAL\IfNull
        DATE_FORMAT: App\DBAL\DateFormat
        # REGEXP_REPLACE: App\DBAL\RegexpReplace
        # REGEXP: App\DBAL\Regexp

when@test:
  doctrine:
    dbal:
      driver: pdo_sqlite
      memory: true
      charset: UTF8

      # IMPORTANT: You MUST configure your server version,
      # either here or in the DATABASE_URL env var (see .env file)
      #server_version: '5.7'
    orm:
      auto_generate_proxy_classes: true
      naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: annotation
          dir: "%kernel.project_dir%/src/Entity"
          prefix: 'App\Entity'
          alias: App
