doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    mapping_types:
          longtext: json

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    enable_lazy_ghost_objects : true
    validate_xml_mapping: true
    report_fields_where_declared: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App

    dql:
      string_functions:
        REPLACE: App\DBAL\Replace
        IFNULL: App\DBAL\IfNull
        DATE_FORMAT: App\DBAL\DateFormat
        # REGEXP_REPLACE: App\DBAL\RegexpReplace
        # REGEXP: App\DBAL\Regexp

when@test:
  doctrine:
    dbal:
      driver: pdo_sqlite
      memory: true
      charset: UTF8

      # IMPORTANT: You MUST configure your server version,
      # either here or in the DATABASE_URL env var (see .env file)
      #server_version: '5.7'
    orm:
      auto_generate_proxy_classes: true
      naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: attribute
          dir: "%kernel.project_dir%/src/Entity"
          prefix: 'App\Entity'
          alias: App

when@prod:
  doctrine:
    orm:
        auto_generate_proxy_classes: false
        # To interpret classes metadata
        # Can be useful if their metadata doesn't change a lot
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        # For DQL to SQL transformation
        # Useful if DQL queries don't change a lot
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        # For results produced by Doctrine (the output is very often hydrated)
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

        # For more info :
        # https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/caching.html
