version: "3.8"
services:

        php:
           user: ${UNAME:-devcoupcrd}
           entrypoint: php.entrypoint
           build:
                   context: .
                   dockerfile: ./docker/php.Dockerfile
                   args:
                           UID: ${UID:-1000}
                           GID: ${GID:-1000}
                           UNAME: ${UNAME:-devcoupcrd}
           volumes:
                - .:/home/devcoupcrd/coupcritique-back
           working_dir: /home/devcoupcrd/coupcritique-back
           extra_hosts:
             - host.docker.internal:host-gateway
           environment:
             PHP_IDE_CONFIG: "serverName=coupcritique-back-docker"
             XDEBUG_MODE: "debug"
             XDEBUG_CONFIG: >-
                idekey=PHPSTORM
                log_level=0
                client_host=host.docker.internal
             MAILER_DSN: smtp://maildev:25

        nginx:
          image: nginx:alpine
          restart: unless-stopped
          volumes:
            - ./:/var/www/html:ro
            - ./docker/application_vhost.conf:/etc/nginx/conf.d/default.conf:ro
          ports:
            - ${SERVER_HOST_PORT:-7800}:80

        db:
           image: mariadb:latest
           volumes:
                - coupcritique_back_data:/var/lib/mysql
           ports:
                - ${MARIADB_PORT:-8336}:3306
           environment:
                   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
                   MYSQL_DATABASE: ${MYSQL_DATABASE:-coupcritique_back}

        adminer:
           image: adminer
           restart: always
           ports:
                - ${ADMINER_HOST_PORT:-8888}:8080

        maildev:
           image: djfarrelly/maildev
           command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
           ports:
                - ${MAILDEV_WEB_PORT:-8700}:80

        matomo:
           image: matomo
           volumes:
                - matomo:/var/www/html # matomo's files
           ports:
                - ${MATOMO_PORT:-8889}:80
           environment:
                   MATOMO_DATABASE_HOST: db
                   MATOMO_DATABASE_ADAPTER: mariadb
                   MATOMO_DATABASE_TABLES_PREFIX: matomo_
                   MATOMO_DATABASE_USERNAME: root
                   MATOMO_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
                   MATOMO_DATABASE_DBNAME: matomo
        redis:
           image: redis:7.0.7

volumes:
        coupcritique_back_data:
        matomo: