default:
  resource: ../../src/Controller/DefaultController.php
  type: attribute

site:
  resource: ../../src/Controller/SiteController.php
  type: attribute

kernel:
  resource: ../../src/Kernel.php
  type: attribute
