api_login_check:
  path: /api/login

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

api:
  resource: ../src/Controller/Api/
  type: attribute
  name_prefix: api_
  prefix: /api
