# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $projectDir: "%kernel.project_dir%"
      $venatusId: "%env(resolve:VENATUS_ID)%"

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/*"
    exclude: "../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous one

  App\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Normalizer\EntityNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags:
      - { name: serializer.normalizer }

  App\Normalizer\CollectionNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags:
      - { name: serializer.normalizer }

  App\Normalizer\FindByNameNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags:
      - { name: serializer.normalizer }

  App\Normalizer\DateTimeNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags:
      - { name: serializer.normalizer }

  App\EventListener\AuthorizeListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 1000 }

  App\EventListener\ContributionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }
      - { name: kernel.event_listener, event: kernel.response }
